'use client';

import { useEffect, useState } from 'react';
import { AppShell } from '@/components/layout/AppShell';
import { Panel } from '@/components/ui/Panel';
import { Button } from '@/components/ui/Button';
import { useStore } from '@/lib/store';
import { computeRisks, getNextActions, caseAge, formatCurrency, STATUSES } from '@/lib/data';
import { FileText, Copy, RefreshCw, AlertTriangle, ClipboardList } from 'lucide-react';
import { clsx } from 'clsx';

function copyToClipboard(text: string) {
  navigator.clipboard.writeText(text);
  const t = document.createElement('div');
  t.textContent = '✓ Copied to clipboard';
  t.style.cssText = `position:fixed;bottom:20px;right:20px;background:#2e844a;color:white;padding:8px 16px;border-radius:4px;font-size:12px;font-weight:600;z-index:9999;box-shadow:0 4px 12px rgba(0,0,0,0.2);`;
  document.body.appendChild(t);
  setTimeout(() => t.remove(), 2000);
}

export default function ReportsPage() {
  const { cases, init } = useStore();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { init(); }, []);
  const [activeTab, setActiveTab] = useState<'weekly' | 'risk' | 'status'>('weekly');

  const today = new Date();
  const dateStr = today.toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' });
  const open = cases.filter(c => !['Closed', 'Cancelled'].includes(c.status));
  const closed = cases.filter(c => c.status === 'Closed');
  const atRisk = open.filter(c => computeRisks(c).length > 0);
  const critical = open.filter(c => computeRisks(c).some(r => r.severity === 'critical'));
  const ages = open.map(caseAge);
  const avgAge = ages.length ? Math.round(ages.reduce((a, b) => a + b, 0) / ages.length) : 0;
  const totalValue = open.reduce((s, c) => s + (c.estimatedValue || 0), 0);
  const overBudget = open.filter(c => c.estimatedValue > c.approvedBudget);

  function weeklyReport() {
    const lines: string[] = [];
    lines.push(`PROCUREMENT WEEKLY STATUS REPORT`);
    lines.push(`Date: ${dateStr} | Prepared by: Priya Sharma, Procurement Lead`);
    lines.push(`${'─'.repeat(64)}`);
    lines.push(``);
    lines.push(`EXECUTIVE SUMMARY`);
    lines.push(`─────────────────`);
    lines.push(`As of ${dateStr}, the procurement team is managing ${open.length} active case(s)`);
    lines.push(`with a combined pipeline value of ${formatCurrency(totalValue)}.`);
    lines.push(`The average case age is ${avgAge} days.`);
    lines.push(``);
    if (atRisk.length > 0) {
      lines.push(`⚠ RISK ALERT: ${atRisk.length} case(s) require attention — ${critical.length} flagged CRITICAL.`);
    } else {
      lines.push(`✅ All cases are progressing within expected timelines.`);
    }
    lines.push(``);
    lines.push(`KEY METRICS`);
    lines.push(`───────────`);
    lines.push(`• Open Cases        : ${open.length}`);
    lines.push(`• Closed Cases      : ${closed.length}`);
    lines.push(`• At-Risk Cases     : ${atRisk.length} (${critical.length} critical)`);
    lines.push(`• Average Age       : ${avgAge} days`);
    lines.push(`• Pipeline Value    : ${formatCurrency(totalValue)}`);
    lines.push(`• Budget Overruns   : ${overBudget.length} case(s)`);
    lines.push(``);
    lines.push(`STATUS BREAKDOWN`);
    lines.push(`────────────────`);
    STATUSES.forEach(s => {
      const count = cases.filter(c => c.status === s).length;
      if (count > 0) lines.push(`• ${s.padEnd(18)}: ${count} case(s)`);
    });
    lines.push(``);
    if (critical.length > 0) {
      lines.push(`CRITICAL CASES — IMMEDIATE ACTION REQUIRED`);
      lines.push(`──────────────────────────────────────────`);
      critical.forEach(c => {
        const risks = computeRisks(c);
        const acts = getNextActions(c, risks);
        lines.push(`[${c.id}] ${c.title}`);
        lines.push(`  Status: ${c.status} | Assigned: ${c.assignedTo} | Age: ${caseAge(c)} days`);
        lines.push(`  Risks : ${risks.map(r => r.type).join(', ')}`);
        lines.push(`  Action: ${acts[0]}`);
        lines.push(``);
      });
    }
    const upcoming = open
      .filter(c => c.expectedClosure)
      .map(c => ({ c, days: Math.ceil((new Date(c.expectedClosure).getTime() - Date.now()) / 86400000) }))
      .filter(({ days }) => days >= 0 && days <= 14)
      .sort((a, b) => a.days - b.days);
    lines.push(`UPCOMING CLOSURES (Next 14 Days)`);
    lines.push(`────────────────────────────────`);
    if (upcoming.length === 0) {
      lines.push(`No cases expected to close in the next 14 days.`);
    } else {
      upcoming.forEach(({ c, days }) => lines.push(`• [${c.id}] ${c.title} — closes in ${days} day(s)`));
    }
    lines.push(``);
    lines.push(`${'─'.repeat(64)}`);
    lines.push(`Auto-generated by ProcureTrack Enterprise on ${dateStr}.`);
    return lines.join('\n');
  }

  function riskReport() {
    if (atRisk.length === 0) return 'No at-risk cases as of this report. All cases are progressing normally.';
    const lines: string[] = [];
    lines.push(`AT-RISK CASES — DETAILED REPORT`);
    lines.push(`${'─'.repeat(56)}`);
    lines.push(``);
    atRisk.forEach((c, i) => {
      const risks = computeRisks(c);
      const acts = getNextActions(c, risks);
      lines.push(`${i + 1}. [${c.id}] ${c.title}`);
      lines.push(`   Priority : ${c.priority}`);
      lines.push(`   Status   : ${c.status}`);
      lines.push(`   Assigned : ${c.assignedTo}`);
      lines.push(`   Age      : ${caseAge(c)} days`);
      lines.push(`   Value    : ${formatCurrency(c.estimatedValue)}`);
      lines.push(`   Risks:`);
      risks.forEach(r => lines.push(`     [${r.severity.toUpperCase()}] ${r.type}: ${r.msg}`));
      lines.push(`   Actions:`);
      acts.forEach(a => lines.push(`     → ${a}`));
      lines.push(``);
    });
    return lines.join('\n');
  }

  function statusReport() {
    const lines: string[] = [];
    lines.push(`ACTIVE CASE STATUS SNAPSHOT`);
    lines.push(`${'─'.repeat(76)}`);
    lines.push(`${'ID'.padEnd(14)} ${'Title'.padEnd(30)} ${'Status'.padEnd(16)} ${'Age'.padEnd(6)} Risk`);
    lines.push(`${'─'.repeat(76)}`);
    open.sort((a, b) => caseAge(b) - caseAge(a)).forEach(c => {
      const risks = computeRisks(c);
      const title = c.title.length > 28 ? c.title.slice(0, 27) + '…' : c.title;
      const riskStr = risks.length === 0 ? '✅ Healthy' : `⚠ ${risks.length} risk(s)`;
      lines.push(`${c.id.padEnd(14)} ${title.padEnd(30)} ${c.status.padEnd(16)} ${(caseAge(c) + 'd').padEnd(6)} ${riskStr}`);
    });
    lines.push(`${'─'.repeat(76)}`);
    lines.push(`Total: ${open.length} active case(s) | Generated: ${dateStr}`);
    return lines.join('\n');
  }

  const TABS = [
    { id: 'weekly' as const, label: 'Weekly Executive Summary', icon: FileText },
    { id: 'risk' as const, label: 'At-Risk Cases Report', icon: AlertTriangle },
    { id: 'status' as const, label: 'Status Snapshot', icon: ClipboardList },
  ];

  const reportContent = activeTab === 'weekly' ? weeklyReport() : activeTab === 'risk' ? riskReport() : statusReport();

  return (
    <AppShell
      title="Reports & Summaries"
      subtitle={`Auto-generated as of ${dateStr}`}
      breadcrumbs={[{ label: 'Reports' }]}
      actions={
        <>
          <Button icon={RefreshCw} size="sm" onClick={() => init()}>Refresh</Button>
          <Button icon={Copy} size="sm" onClick={() => copyToClipboard(reportContent)}>Copy Report</Button>
        </>
      }
    >
      {/* Report meta cards */}
      <div className="grid grid-cols-3 gap-4 mb-5">
        <div className="bg-white border border-enterprise-200 rounded shadow-sm p-3">
          <div className="text-xs text-text-muted mb-0.5">Report Date</div>
          <div className="text-sm font-semibold text-text-primary">{dateStr}</div>
        </div>
        <div className="bg-white border border-enterprise-200 rounded shadow-sm p-3">
          <div className="text-xs text-text-muted mb-0.5">Reporting Period</div>
          <div className="text-sm font-semibold text-text-primary">Weekly Summary</div>
        </div>
        <div className="bg-white border border-enterprise-200 rounded shadow-sm p-3">
          <div className="text-xs text-text-muted mb-0.5">Prepared By</div>
          <div className="text-sm font-semibold text-text-primary">Priya Sharma</div>
        </div>
      </div>

      <Panel noPad>
        {/* Tab bar */}
        <div className="flex border-b border-enterprise-200 bg-enterprise-50">
          {TABS.map(({ id, label, icon: Icon }) => (
            <button
              key={id}
              onClick={() => setActiveTab(id)}
              className={clsx(
                'flex items-center gap-2 px-5 py-3 text-sm font-medium border-b-2 -mb-px transition-all',
                activeTab === id
                  ? 'border-brand text-brand bg-white'
                  : 'border-transparent text-text-secondary hover:text-text-primary hover:bg-white/60'
              )}
            >
              <Icon size={14} />
              {label}
            </button>
          ))}
        </div>

        {/* Report content */}
        <div className="p-5">
          <div className="flex items-center justify-between mb-3">
            <span className="text-xs text-text-muted">Auto-generated report — copy or export for stakeholder use</span>
            <Button icon={Copy} size="xs" onClick={() => copyToClipboard(reportContent)}>Copy</Button>
          </div>
          <pre className="w-full bg-enterprise-50 border border-enterprise-200 rounded p-4 text-xs font-mono text-text-secondary leading-relaxed overflow-x-auto whitespace-pre-wrap max-h-[520px] overflow-y-auto">
            {reportContent}
          </pre>
        </div>
      </Panel>
    </AppShell>
  );
}
